// <auto-generated />
namespace RepositoryLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FinalCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinalCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201909241036432_FinalCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
